FROM php:8.4-fpm

RUN apt-get update && apt-get install -y --no-install-recommends \
    git curl unzip zip \
    libicu-dev \
    libzip-dev \
    libpng-dev libjpeg-dev libfreetype6-dev \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-configure gd --with-jpeg --with-freetype

RUN docker-php-ext-install -j$(nproc) \
    bcmath exif pcntl intl zip gd opcache pdo pdo_pgsql

RUN pecl install redis && docker-php-ext-enable redis
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

RUN { \
      echo "pm = dynamic"; \
      echo "pm.max_children = 20"; \
      echo "pm.start_servers = 2"; \
      echo "pm.min_spare_servers = 2"; \
      echo "pm.max_spare_servers = 8"; \
      echo "pm.max_requests = 500"; \
    } > /usr/local/etc/php-fpm.d/zz-www.conf

RUN { \
      echo "opcache.enable=1"; \
      echo "opcache.validate_timestamps=0"; \
      echo "opcache.jit=1255"; \
      echo "opcache.jit_buffer_size=64M"; \
      echo "memory_limit=512M"; \
      echo "upload_max_filesize=32M"; \
      echo "post_max_size=32M"; \
      echo "max_execution_time=120"; \
    } > /usr/local/etc/php/conf.d/zz-custom.ini

USER www-data
